/*init data***/
INSERT INTO organization (company_name, active) 
VALUES 
('IDA', true);
INSERT INTO user (user_name, password, role, active, organization_id) 
VALUES
('idaAdmin', 'b1d2e11b343783a14f6f8362b294bb22', 'ADMIN', true, (SELECT id FROM organization where company_name = 'IDA'));

  
INSERT INTO category (NAME, category_TYPE, DESCRIPTION, SORT, PARENT) 
VALUES 
('BPM', 'JAVA_COMMAND', 'BPM', 1, null),
('UI', 'JAVASCRIPT_COMMAND', 'UI', 2, null),
('BPMAssertion', 'JAVA_COMMAND', 'BPM Assertion', 3, null),
('UIAssertion', 'JAVASCRIPT_COMMAND', 'UI Assertion',4, null),
('Utility', 'JAVA_COMMAND', 'Utility',5, null),
('Custom', 'GROUP_COMMAND', 'Custom',6, null);
  
INSERT INTO command (NAME, DESCRIPTION, CATEGORY_ID, VERBALIZATION, TAKESCREENSHOT) 
VALUES 
('addContext', 'Add a key-value pair to list of context', (SELECT ID FROM category WHERE NAME = 'Utility'), 'Add {{Parameters.value}} into list of system context with key {{Parameters.key}}.', false),
('dateString', 'generate date string before/after number of days of today, negative number of days means before today, positive number of days means after today. If the key is not specified, then the default key is "DATE_STRING". You can use the date string by ${context.DATE_STRING}', (SELECT ID FROM category WHERE NAME = 'Utility'), 'Save a date string into system context with key {{Parameters.key}}.', false),
('debug', 'Command for debug, case will stop at this step', (SELECT ID FROM category WHERE NAME = 'Utility'), 'Debug {{Parameters.log}}.', false),
('putContext', 'Put a key-value pair to context', (SELECT ID FROM category WHERE NAME = 'Utility'), 'Save the value {{Parameters.value}} into system context with key {{Parameters.key}}.', false),
('wait', 'Wait for specify seconds', (SELECT ID FROM category WHERE NAME = 'Utility'), 'Wait for {{Parameters.time}} seconds.', false),
('randomString', 'generate random string, use it by: ${context.RANDOM_STRING}', (SELECT ID FROM category WHERE NAME = 'Utility'), 'Save a random string into system context with key RANDOM_STRING.', false),
('randomNumber', 'generate random number, use it by: ${context.RANDOM_NUMBER}', (SELECT ID FROM category WHERE NAME = 'Utility'), 'Save a random number into system context with key RANDOM_NUMBER.', false),
('bpmFileDropzone', 'Upload file to BPM server by Dropzone control', (SELECT ID FROM category WHERE NAME = 'UI'), 'Upload file {{Parameters.value}}.', true),
('bpmFileUploader', 'Upload file to the BPM server', (SELECT ID FROM category WHERE NAME = 'UI'), 'Upload file {{Parameters.value}}.', true),
('checkbox', 'Set checkbox value', (SELECT ID FROM category WHERE NAME = 'UI'), 'Select {{Parameters.value}} to {{Parameters.label}}.', true),
('click', 'Click a element by id, css or xpath', (SELECT ID FROM category WHERE NAME = 'UI'), 'Click {{Parameters.value}}.', true),
('coachControl', 'Set Coach Control value by control ID', (SELECT ID FROM category WHERE NAME = 'UI'), 'Set {{Parameters.value}} to coach control {{Parameters.controlId}}.', true),
('confirmCancel', 'Cancel the alert window', (SELECT ID FROM category WHERE NAME = 'UI'), 'Click the Cancel button of confirm dialog.', true),
('confirmOK', 'Confirm the alert window', (SELECT ID FROM category WHERE NAME = 'UI'), 'Click the Ok button of confirm dialog.', true),
('doubleClick', 'Double click a element by id, css or xpath', (SELECT ID FROM category WHERE NAME = 'UI'), 'Double click {{Parameters.value}}.', true),
('file', 'Set file element', (SELECT ID FROM category WHERE NAME = 'UI'), 'Upload file {{Parameters.value}}.', true),
('open', 'Open an URL', (SELECT ID FROM category WHERE NAME = 'UI'), 'Open url {{Parameters.url}} .', true),
('close', 'Close browser', (SELECT ID FROM category WHERE NAME = 'UI'), 'Close browser.', false),
('radio', 'Set radio control value', (SELECT ID FROM category WHERE NAME = 'UI'), 'Set {{Parameters.value}} to {{Parameters.label}}.', true),
('saveCoachControl', 'Save Coach Control binding value into context. For complex binding value object, you can get the value by property', (SELECT ID FROM category WHERE NAME = 'UI'), 'Save the binding value of coach control {{Parameters.controlId}} into system context with key {{Parameters.key}}.', true),
('saveText', 'Save text into context', (SELECT ID FROM category WHERE NAME = 'UI'), 'Save the text of element {{Parameters.elementId}} into system context with key {{Parameters.key}}.', true),
('select', 'Set select control value', (SELECT ID FROM category WHERE NAME = 'UI'), 'Select {{Parameters.value}} to {{Parameters.label}}.', true),
('selectWindow', 'Select window by the window info', (SELECT ID FROM category WHERE NAME = 'UI'), 'Select window {{Parameters.info}}.', true),
('text', 'Set text control value', (SELECT ID FROM category WHERE NAME = 'UI'), 'Set {{Parameters.value}} to {{Parameters.label}}.', true),
('waitElement', 'Wait a element visible/hidden/editable/readonly', (SELECT ID FROM category WHERE NAME = 'UI'), 'Wait element {{Parameters.elementId}} {{Parameters.type}}', true),
('waitTextPresent', 'Wait the text display on the html', (SELECT ID FROM category WHERE NAME = 'UI'), 'Wait text {{Parameters.text}} present', true),
('ajaxGet', 'Process a AJAX Get request', (SELECT ID FROM category WHERE NAME = 'UI'), 'Get {{Parameters.url}} ', false),
('ajaxPost', 'Process a AJAX Post request', (SELECT ID FROM category WHERE NAME = 'UI'), 'POST {{Parameters.url}} with data {{Parameters.postData}}', false),
('ajaxPut', 'Process a AJAX Put request', (SELECT ID FROM category WHERE NAME = 'UI'), 'PUT {{Parameters.url}} with data {{Parameters.postData}}', false),
('ajaxDel', 'Process a AJAX Delete request', (SELECT ID FROM category WHERE NAME = 'UI'), 'DELETE {{Parameters.url}} with data {{Parameters.postData}}', false),
('assertButtons', 'Asset button text', (SELECT ID FROM category WHERE NAME = 'UIAssertion'), 'Assert that the button {{Parameters.texts}} is {{Parameters.expectedVisibility}}.', true),
('assertCheckbox', 'Assert checkbox value and options', (SELECT ID FROM category WHERE NAME = 'UIAssertion'), 'Assert that the checkbox {{Parameters.controlId}} checked labels are {{Parameters.checkedLabels}}.', true),
('assertCoachControl', 'Assert Coach Control binding value and visibility, it only supports String, Number, Date and Boolean type of binding value now. Either of controlId or label is required. The controlId is the coach view control id, label is the coach view label', (SELECT ID FROM category WHERE NAME = 'UIAssertion'), 'Assert that the control {{Parameters.label}} value is {{Parameters.expectedValue}}.', true),
('assertDatePicker', 'Assert Date Time Picker value', (SELECT ID FROM category WHERE NAME = 'UIAssertion'), 'Assert that the date time picker {{Parameters.controlId}} is {{Parameters.expectedDate}}.', true),
('assertElement', 'Assert the element value and visibility', (SELECT ID FROM category WHERE NAME = 'UIAssertion'), 'Assert that the element {{Parameters.elementId}} value is {{Parameters.expectedValue}}.', true),
('assertInputText', 'Assert Coach Text value, If you check the regular expression,it will use expected value as regular expression to match the actual value', (SELECT ID FROM category WHERE NAME = 'UIAssertion'), 'Assert that the text {{Parameters.controlId}} value is {{Parameters.expectedValue}}.', true),
('assertOutputText', 'Assert Output Text value', (SELECT ID FROM category WHERE NAME = 'UIAssertion'), 'Assert that the output text {{Parameters.controlId}} value is {{Parameters.expectedValue}}.', true),
('assertRadio', 'Assert Radio value and options', (SELECT ID FROM category WHERE NAME = 'UIAssertion'), 'Assert that the radio group {{Parameters.controlId}} checked label is {{Parameters.checkedLabel}}.', true),
('assertSelect', 'Assert Select value', (SELECT ID FROM category WHERE NAME = 'UIAssertion'), 'Assert that the select {{Parameters.controlId}} value is {{Parameters.expectedValue}}.', true),
('assertSwitch', 'Assert Switch Button value', (SELECT ID FROM category WHERE NAME = 'UIAssertion'), 'Assert that the switch button {{Parameters.controlId}} value is {{Parameters.expectedValue}}.', true),
('assertTableContent', 'Assert Table Content', (SELECT ID FROM category WHERE NAME = 'UIAssertion'), 'Assert that the table {{Parameters.controlId}} with row {{Parameters.rowNum}} and column {{Parameters.columnName}} value is {{Parameters.expectedValue}}.', true),
('assertTableRows', 'Assert Table Rows', (SELECT ID FROM category WHERE NAME = 'UIAssertion'), 'Assert that the table {{Parameters.controlId}} has {{Parameters.expectedRows}} rows.', true),
('assertTextarea', 'Check Text area value', (SELECT ID FROM category WHERE NAME = 'UIAssertion'), 'Assert that the textarea {{Parameters.controlId}} value is {{Parameters.expectedValue}}.', true),
('assertTextNotPresent', '', (SELECT ID FROM category WHERE NAME = 'UIAssertion'), 'Assert that the text {{Parameters.text}}  is not present.', true),
('assertTextPresent', '', (SELECT ID FROM category WHERE NAME = 'UIAssertion'), 'Assert that the text {{Parameters.text}}  is present .', true),
('assertValidationPassed', 'Check whether the coach page is passed the validation or not', (SELECT ID FROM category WHERE NAME = 'UIAssertion'), 'Assert that the coach view page is pass validation', true),
('loginBPMoC', 'Login BPMoC, only support IBM Account and Local Account', (SELECT ID FROM category WHERE NAME = 'BPM'), '{{Step.BpmUser}} login BPM on Cloud portal.', true),
('loginPortal', 'Login BPM Portal', (SELECT ID FROM category WHERE NAME = 'BPM'), '{{Step.BpmUser}} login Portal.', true),
('openInstanceDetail', 'Open the instance detail page for current instance', (SELECT ID FROM category WHERE NAME = 'BPM'), 'Open the instance detail page of current instance.', true),
('startProcess', 'Start a BPM process by REST API, only exposed process are supported by default. Install BPM IDA Toolkit to support all processes.', (SELECT ID FROM category WHERE NAME = 'BPM'), '{{Step.BpmUser}} launches the process {{Parameters.process}}.', false),
('startHumanService', 'Start a human service.', (SELECT ID FROM category WHERE NAME = 'BPM'), '{{Step.BpmUser}} launches the human Service {{Parameters.service}}.', true),
('startExposedHertiageHumanService', 'Start a exposed heritage human service, please make sure the human service is exposed to a specify team.', (SELECT ID FROM category WHERE NAME = 'BPM'), '{{Step.BpmUser}} launches the exposed heritage human service {{Parameters.service}}.', true),
('startAjaxService', 'Start a ajax service by REST API', (SELECT ID FROM category WHERE NAME = 'BPM'), '{{Step.BpmUser}} launches the AJAX service {{Parameters.service}}.', false),
('startSystemService', 'Start a system service by REST API, please install BPM IDA Toolkit to support system service.', (SELECT ID FROM category WHERE NAME = 'BPM'), '{{Step.BpmUser}} launches the system service {{Parameters.service}}.', false),
('startSQLQuery', 'Perform SQL Query by REST API, please install BPM IDA Toolkit to support SQL Query.', (SELECT ID FROM category WHERE NAME = 'BPM'), '{{Step.BpmUser}} executes sql {{Parameters.sql}} on database {{Parameters.dataPARAM_SOURCEName}}.', false),
('startUCA', 'Start a UCA', (SELECT ID FROM category WHERE NAME = 'BPM'), '{{Step.BpmUser}} launches UCA {{Parameters.uca}}.', false),
('startServiceFlow', 'Start a service flow by REST API, please install BPM Testing Asset Toolkit to support system service.', (SELECT ID FROM category WHERE NAME = 'BPM'), '{{Step.BpmUser}} launches service flow {{Parameters.service}}.', false),
('startAdHoc', 'Start AdHoc Event', (SELECT ID FROM category WHERE NAME = 'BPM'), '{{Step.BpmUser}} launches AdHoc event {{Parameters.adHocName}}.', false),
('runAdHocActivity', 'Start AdHoc Activity', (SELECT ID FROM category WHERE NAME = 'BPM'), '{{Step.BpmUser}} launches AdHoc activity {{Parameters.adHocActivityName}}.', true),
('runTaskByDisplayName', 'Run Task by Display Name', (SELECT ID FROM category WHERE NAME = 'BPM'), '{{Step.BpmUser}} launches task {{Parameters.taskName}} by display name.', true),
('runTaskByActivityName', 'Run Task by Activity Name', (SELECT ID FROM category WHERE NAME = 'BPM'), '{{Step.BpmUser}} launches task {{Parameters.taskName}} by activity name.', true),
('assignTask', 'Assign task to user', (SELECT ID FROM category WHERE NAME = 'BPM'), '{{Step.BpmUser}} assigns task {{Parameters.taskName}} to {{Parameters.toUser}}.', false),
('claimTask', 'Start a task', (SELECT ID FROM category WHERE NAME = 'BPM'), '{{Step.BpmUser}} claims task {{Parameters.taskName}}.', false),
('finishTask', 'Finish a task', (SELECT ID FROM category WHERE NAME = 'BPM'), '{{Step.BpmUser}} finishes task {{Parameters.taskName}}.', false),
('addInstanceId', 'Add a process instance id to context, use it by: ${context.currentInstanceId}', (SELECT ID FROM category WHERE NAME = 'BPM'), 'Set current instance id to {{Parameters.instanceId}}.', false),
('getTaskIdByName', 'Get the task ID by name, use it by: ${context.currentTaskId}', (SELECT ID FROM category WHERE NAME = 'BPM'), 'Get task ID by task name {{Parameters.taskName}}.', false),
('getLatestInstanceIdByProcess', 'Get the latest process instance id by process name, use it by: ${context.currentInstanceId}', (SELECT ID FROM category WHERE NAME = 'BPM'), 'Set latest instance ID of process {{Parameters.processName}} into system context with key currentInstanceId', false),
('getInstanceIdByInstanceName', 'Get the process instance id by process name and instance name, use it by: ${context.currentInstanceId}', (SELECT ID FROM category WHERE NAME = 'BPM'), 'Set instance id by instance name {{Parameters.instanceName}} into system context with key currentInstanceId.', false),
('getInstanceIdByTaskName', 'Get the process instance id by process name and task subject name, use it by: ${context.currentInstanceId}', (SELECT ID FROM category WHERE NAME = 'BPM'), 'Set instance ID by task name {{Parameters.taskName}} into system context with key currentInstanceId.', false),
('getInstanceIdByTaskUrl', 'Get the process instance id by the task id in url, use it by: ${context.currentInstanceId}', (SELECT ID FROM category WHERE NAME = 'BPM'), 'Set instance ID by task url into system context with key currentInstanceId.', false),
('getInstanceIdByBusinessData', 'Get the process instance id by process name and business data, use it by: ${context.currentInstanceId}', (SELECT ID FROM category WHERE NAME = 'BPM'), 'Set instance ID by business data alias {{Parameters.businessDataAlias}} into system context with key currentInstanceId.', false),
('fireTimer', 'Fire timer for the current instance', (SELECT ID FROM category WHERE NAME = 'BPM'), 'Trigger a timer event on token {{Parameters.token}}.', false),
('startRestApi', 'Check Rest API', (SELECT ID FROM category WHERE NAME = 'BPM'), 'REST API {{Parameters.apiName}} is invoked.', false),
('assertProcessInstanceStatus', 'Check current process instance status', (SELECT ID FROM category WHERE NAME = 'BPMAssertion'), 'Assert that the current process instance status is {{Parameters.instanceStatus}}.', false),
('assertProcessInstanceData', 'asset the data of current process instance', (SELECT ID FROM category WHERE NAME = 'BPMAssertion'), 'Assert that the current process instance data is {{Parameters.expectedValue}}.', false),
('assertTaskAssignmentByUser', 'Check  task is assigned to the correct user', (SELECT ID FROM category WHERE NAME = 'BPMAssertion'), 'Assert that the task {{Parameters.taskName}} is assigned to {{Step.BpmUser}}.', false),
('assertTaskStatus', 'Check the status of a BPM task for the current process instance', (SELECT ID FROM category WHERE NAME = 'BPMAssertion'), 'Assert that the task {{Parameters.taskName}} status is {{Parameters.taskStatus}}.', false),
('assertNextTaskName', 'Check the next task name of current process instance', (SELECT ID FROM category WHERE NAME = 'BPMAssertion'), 'Assert that the next task name is {{Parameters.taskName}} .', false),
('assertTaskNotGenerated', 'Check the task name of current process instance is not generated', (SELECT ID FROM category WHERE NAME = 'BPMAssertion'), 'Assert that the task {{Parameters.taskName}} is not generated.', false),
('assertTaskData', 'Check the task data of current process instance', (SELECT ID FROM category WHERE NAME = 'BPMAssertion'), 'Assert that the task {{Parameters.taskName}} data is {{Parameters.expectedValue}} .', false),
('assertServiceData', 'Check the current service data', (SELECT ID FROM category WHERE NAME = 'BPMAssertion'), 'Assert that the current service data is {{Parameters.expectedValue}}.', false);


INSERT INTO command_parameter(DISPLAY_NAME, PARAMETER_NAME, PARAMETER_TYPE, PARAM_SOURCE, CHECKED, UNCHECKED, PARAM_REGEXP, HIDDEN, COMMAND_ID) VALUES 
('Key', 'key', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'addContext' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'Utility'))),
('Value', 'value', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'addContext' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'Utility'))),
('Key', 'key', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'dateString' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'Utility'))),
('Days', 'days', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'dateString' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'Utility'))),
('Format', 'format', 'combo', 'getDateFormatList', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'dateString' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'Utility'))),
('Log', 'log', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'debug' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'Utility'))),
('Key', 'key', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'putContext' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'Utility'))),
('Value', 'value', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'putContext' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'Utility'))),
('Time', 'time', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'wait' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'Utility'))),
('Length', 'length', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'randomString' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'Utility'))),
('Length', 'length', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'randomNumber' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'Utility'))),
('Value', 'value', 'combo', 'getFileNameList', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'bpmFileDropzone' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UI'))),
('Control ID', 'controlId', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'bpmFileDropzone' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UI'))),
('Value', 'value', 'combo', 'getFileNameList', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'bpmFileUploader' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UI'))),
('Control ID', 'controlId', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'bpmFileUploader' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UI'))),
('Value', 'value', 'textarea', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'checkbox' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UI'))),
('Control ID', 'controlId', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'checkbox' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UI'))),
('Label', 'label', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'checkbox' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UI'))),
('Element ID', 'elementId', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'checkbox' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UI'))),
('Element CSS', 'elementCss', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'checkbox' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UI'))),
('XPATH', 'xpath', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'checkbox' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UI'))),
('Value', 'value', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'click' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UI'))),
('Type', 'type', 'combo', 'getClickTypeList', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'click' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UI'))),
('Element ID', 'elementId', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'click' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UI'))),
('Element CSS', 'elementCss', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'click' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UI'))),
('XPATH', 'xpath', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'click' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UI'))),
('Value', 'value', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'coachControl' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UI'))),
('Value Type', 'valueType', 'combo', 'getValueTypeList', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'coachControl' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UI'))),
('Control ID', 'controlId', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'coachControl' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UI'))),
('Label', 'label', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'coachControl' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UI'))),
('Element ID', 'elementId', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'coachControl' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UI'))),
('Element CSS', 'elementCss', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'coachControl' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UI'))),
('XPATH', 'xpath', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'coachControl' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UI'))),
('Default Value', 'defaultValue', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'coachControl' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UI'))),
('Value', 'value', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'doubleClick' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UI'))),
('Element ID', 'elementId', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'doubleClick' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UI'))),
('Element CSS', 'elementCss', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'doubleClick' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UI'))),
('XPATH', 'xpath', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'doubleClick' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UI'))),
('Value', 'value', 'combo', 'getFileNameList', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'file' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UI'))),
('Element ID', 'elementId', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'file' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UI'))),
('Element CSS', 'elementCss', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'file' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UI'))),
('XPATH', 'xpath', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'file' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UI'))),
('URL', 'url', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'open' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UI'))),
('Value', 'value', 'textarea', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'radio' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UI'))),
('Control ID', 'controlId', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'radio' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UI'))),
('Label', 'label', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'radio' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UI'))),
('Element ID', 'elementId', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'radio' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UI'))),
('Element CSS', 'elementCss', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'radio' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UI'))),
('XPATH', 'xpath', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'radio' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UI'))),
('Key', 'key', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'saveCoachControl' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UI'))),
('Control ID', 'controlId', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'saveCoachControl' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UI'))),
('Label', 'label', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'saveCoachControl' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UI'))),
('Property', 'property', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'saveCoachControl' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UI'))),
('Key', 'key', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'saveText' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UI'))),
('Element ID', 'elementId', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'saveText' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UI'))),
('Element CSS', 'elementCss', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'saveText' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UI'))),
('XPATH', 'xpath', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'saveText' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UI'))),
('Value', 'value', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'select' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UI'))),
('Control ID', 'controlId', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'select' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UI'))),
('Label', 'label', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'select' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UI'))),
('Element ID', 'elementId', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'select' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UI'))),
('Element CSS', 'elementCss', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'select' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UI'))),
('XPATH', 'xpath', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'select' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UI'))),
('Info', 'info', 'combo', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'selectWindow' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UI'))),
('Value', 'value', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'text' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UI'))),
('Control ID', 'controlId', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'text' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UI'))),
('Label', 'label', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'text' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UI'))),
('Element ID', 'elementId', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'text' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UI'))),
('Element CSS', 'elementCss', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'text' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UI'))),
('XPATH', 'xpath', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'text' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UI'))),
('Type', 'type', 'combo', 'getWaitElementTypes', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'waitElement' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UI'))),
('Timeout', 'timeout', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'waitElement' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UI'))),
('Element ID', 'elementId', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'waitElement' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UI'))),
('Element CSS', 'elementCss', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'waitElement' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UI'))),
('XPATH', 'xpath', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'waitElement' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UI'))),
('Text', 'text', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'waitTextPresent' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UI'))),
('Timeout', 'timeout', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'waitTextPresent' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UI'))),
('URL', 'url', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'ajaxGet' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UI'))),
('URL', 'url', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'ajaxPost' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UI'))),
('Post Data', 'postData', 'textarea', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'ajaxPost' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UI'))),
('URL', 'url', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'ajaxPut' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UI'))),
('Post Data', 'postData', 'textarea', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'ajaxPut' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UI'))),
('URL', 'url', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'ajaxDel' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UI'))),
('Post Data', 'postData', 'textarea', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'ajaxDel' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UI'))),
('Texts', 'texts', 'textarea', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'assertButtons' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UIAssertion'))),
('Expected Visibility', 'expectedVisibility', 'combo', 'getButtonVisibilities', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'assertButtons' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UIAssertion'))),
('Control ID', 'controlId', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'assertCheckbox' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UIAssertion'))),
('Label', 'label', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'assertCheckbox' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UIAssertion'))),
('Element ID', 'elementId', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'assertCheckbox' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UIAssertion'))),
('Element CSS', 'elementCss', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'assertCheckbox' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UIAssertion'))),
('XPATH', 'xpath', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'assertCheckbox' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UIAssertion'))),
('Checked Labels', 'checkedLabels', 'textarea', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'assertCheckbox' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UIAssertion'))),
('Expected Options', 'expectedOptions', 'textarea', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'assertCheckbox' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UIAssertion'))),
('Control ID', 'controlId', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'assertCoachControl' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UIAssertion'))),
('Label', 'label', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'assertCoachControl' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UIAssertion'))),
('Element ID', 'elementId', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'assertCoachControl' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UIAssertion'))),
('Element CSS', 'elementCss', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'assertCoachControl' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UIAssertion'))),
('XPATH', 'xpath', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'assertCoachControl' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UIAssertion'))),
('Expected Value', 'expectedValue', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'assertCoachControl' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UIAssertion'))),
('Expected Value Type', 'expectedValueType', 'combo', 'getValueTypeList', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'assertCoachControl' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UIAssertion'))),
('Expected Visibility', 'expectedVisibility', 'combo', 'getVisibilityList', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'assertCoachControl' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UIAssertion'))),
('Control ID', 'controlId', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'assertDatePicker' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UIAssertion'))),
('Label', 'label', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'assertDatePicker' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UIAssertion'))),
('Element ID', 'elementId', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'assertDatePicker' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UIAssertion'))),
('Element CSS', 'elementCss', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'assertDatePicker' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UIAssertion'))),
('XPATH', 'xpath', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'assertDatePicker' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UIAssertion'))),
('Expected Date', 'expectedDate', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'assertDatePicker' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UIAssertion'))),
('Element ID', 'elementId', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'assertElement' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UIAssertion'))),
('Element CSS', 'elementCss', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'assertElement' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UIAssertion'))),
('XPATH', 'xpath', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'assertElement' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UIAssertion'))),
('Expected Value', 'expectedValue', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'assertElement' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UIAssertion'))),
('Expected Visibility', 'expectedVisibility', 'combo', 'getVisibilityList', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'assertElement' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UIAssertion'))),
('Control ID', 'controlId', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'assertInputText' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UIAssertion'))),
('Label', 'label', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'assertInputText' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UIAssertion'))),
('Element ID', 'elementId', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'assertInputText' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UIAssertion'))),
('Element CSS', 'elementCss', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'assertInputText' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UIAssertion'))),
('XPATH', 'xpath', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'assertInputText' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UIAssertion'))),
('Expected Value', 'expectedValue', 'text', '', '', '', 'true', '', (SELECT ID FROM command WHERE NAME = 'assertInputText' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UIAssertion'))),
('Expected Max Length', 'expectedMaxLength', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'assertInputText' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UIAssertion'))),
('Control ID', 'controlId', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'assertOutputText' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UIAssertion'))),
('Label', 'label', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'assertOutputText' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UIAssertion'))),
('Element ID', 'elementId', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'assertOutputText' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UIAssertion'))),
('Element CSS', 'elementCss', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'assertOutputText' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UIAssertion'))),
('XPATH', 'xpath', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'assertOutputText' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UIAssertion'))),
('Expected Value', 'expectedValue', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'assertOutputText' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UIAssertion'))),
('Control ID', 'controlId', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'assertRadio' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UIAssertion'))),
('Label', 'label', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'assertRadio' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UIAssertion'))),
('Element ID', 'elementId', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'assertRadio' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UIAssertion'))),
('Element CSS', 'elementCss', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'assertRadio' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UIAssertion'))),
('XPATH', 'xpath', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'assertRadio' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UIAssertion'))),
('Checked Label', 'checkedLabel', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'assertRadio' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UIAssertion'))),
('Expected Options', 'expectedOptions', 'textarea', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'assertRadio' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UIAssertion'))),
('Control ID', 'controlId', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'assertSelect' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UIAssertion'))),
('Label', 'label', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'assertSelect' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UIAssertion'))),
('Element ID', 'elementId', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'assertSelect' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UIAssertion'))),
('Element CSS', 'elementCss', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'assertSelect' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UIAssertion'))),
('XPATH', 'xpath', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'assertSelect' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UIAssertion'))),
('Expected Value', 'expectedValue', 'textarea', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'assertSelect' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UIAssertion'))),
('Expected Options', 'expectedOptions', 'textarea', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'assertSelect' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UIAssertion'))),
('Control ID', 'controlId', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'assertSwitch' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UIAssertion'))),
('Label', 'label', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'assertSwitch' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UIAssertion'))),
('Element ID', 'elementId', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'assertSwitch' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UIAssertion'))),
('Element CSS', 'elementCss', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'assertSwitch' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UIAssertion'))),
('XPATH', 'xpath', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'assertSwitch' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UIAssertion'))),
('Expected Value', 'expectedValue', 'combo', 'getSwitchValues', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'assertSwitch' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UIAssertion'))),
('Control ID', 'controlId', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'assertTableContent' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UIAssertion'))),
('Column Name', 'columnName', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'assertTableContent' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UIAssertion'))),
('Column Number', 'columnNum', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'assertTableContent' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UIAssertion'))),
('Row Number', 'rowNum', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'assertTableContent' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UIAssertion'))),
('Expected Value', 'expectedValue', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'assertTableContent' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UIAssertion'))),
('Control ID', 'controlId', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'assertTableRows' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UIAssertion'))),
('Expected Rows', 'expectedRows', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'assertTableRows' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UIAssertion'))),
('Control ID', 'controlId', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'assertTextarea' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UIAssertion'))),
('Label', 'label', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'assertTextarea' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UIAssertion'))),
('Element ID', 'elementId', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'assertTextarea' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UIAssertion'))),
('Element CSS', 'elementCss', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'assertTextarea' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UIAssertion'))),
('XPATH', 'xpath', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'assertTextarea' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UIAssertion'))),
('Expected Value', 'expectedValue', 'textarea', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'assertTextarea' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UIAssertion'))),
('Text', 'text', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'assertTextNotPresent' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UIAssertion'))),
('Text', 'text', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'assertTextPresent' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'UIAssertion'))),
('User', 'user', 'combo', 'getUserNameList', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'loginBPMoC' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPM'))),
('User', 'user', 'combo', 'getUserNameList', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'loginPortal' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPM'))),
('User', 'user', 'combo', 'getUserNameList', '', '', '', 'BPMoC', (SELECT ID FROM command WHERE NAME = 'startProcess' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPM'))),
('Process', 'process', 'combo', 'getProcessList', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'startProcess' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPM'))),
('Params', 'params', 'json', 'getProcessInputs', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'startProcess' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPM'))),
('Toolkit Name', 'toolkitName', 'text', '', '', '', '', 'true', (SELECT ID FROM command WHERE NAME = 'startProcess' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPM'))),
('User', 'user', 'combo', 'getUserNameList', '', '', '', 'BPMoC', (SELECT ID FROM command WHERE NAME = 'startHumanService' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPM'))),
('Service', 'service', 'combo', 'getHumanServiceList', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'startHumanService' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPM'))),
('Params', 'params', 'json', 'getHumanServiceInputs', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'startHumanService' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPM'))),
('Toolkit Name', 'toolkitName', 'text', '', '', '', '', 'true', (SELECT ID FROM command WHERE NAME = 'startHumanService' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPM'))),
('User', 'user', 'combo', 'getUserNameList', '', '', '', 'BPMoC', (SELECT ID FROM command WHERE NAME = 'startExposedHertiageHumanService' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPM'))),
('Service', 'service', 'combo', 'getHeritageHumanServiceList', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'startExposedHertiageHumanService' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPM'))),
('Params', 'params', 'json', 'getServiceInputs', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'startExposedHertiageHumanService' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPM'))),
('Toolkit Name', 'toolkitName', 'text', '', '', '', '', 'true', (SELECT ID FROM command WHERE NAME = 'startExposedHertiageHumanService' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPM'))),
('Exception', 'exception', 'checkbox', '', 'true', 'false', '', '', (SELECT ID FROM command WHERE NAME = 'startAjaxService' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPM'))),
('User', 'user', 'combo', 'getUserNameList', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'startAjaxService' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPM'))),
('Service', 'service', 'combo', 'getAjaxServiceList', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'startAjaxService' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPM'))),
('Params', 'params', 'json', 'getServiceInputs', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'startAjaxService' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPM'))),
('Expected Output', 'expectedOutput', 'json', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'startAjaxService' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPM'))),
('Toolkit Name', 'toolkitName', 'text', '', '', '', '', 'true', (SELECT ID FROM command WHERE NAME = 'startAjaxService' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPM'))),
('Json Path', 'jsonPath', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'startAjaxService' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPM'))),
('Variable Name', 'variableName', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'startAjaxService' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPM'))),
('Exception', 'exception', 'checkbox', '', 'true', 'false', '', '', (SELECT ID FROM command WHERE NAME = 'startSystemService' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPM'))),
('User', 'user', 'combo', 'getUserNameList', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'startSystemService' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPM'))),
('Service', 'service', 'combo', 'getSystemServiceList', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'startSystemService' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPM'))),
('Params', 'params', 'json', 'getServiceInputs', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'startSystemService' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPM'))),
('Expected Output', 'expectedOutput', 'json', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'startSystemService' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPM'))),
('Toolkit Name', 'toolkitName', 'text', '', '', '', '', 'true', (SELECT ID FROM command WHERE NAME = 'startSystemService' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPM'))),
('Json Path', 'jsonPath', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'startSystemService' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPM'))),
('Variable Name', 'variableName', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'startSystemService' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPM'))),
('User', 'user', 'combo', 'getUserNameList', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'startSQLQuery' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPM'))),
('SQL', 'sql', 'textarea', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'startSQLQuery' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPM'))),
('Max Rows', 'maxRows', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'startSQLQuery' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPM'))),
('Expected Rows', 'expectedRows', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'startSQLQuery' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPM'))),
('Data Source Name', 'dataSourceName', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'startSQLQuery' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPM'))),
('Expected Output', 'expectedOutput', 'json', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'startSQLQuery' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPM'))),
('Json Path', 'jsonPath', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'startSQLQuery' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPM'))),
('Variable Name', 'variableName', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'startSQLQuery' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPM'))),
('User', 'user', 'combo', 'getUserNameList', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'startUCA' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPM'))),
('UCA', 'uca', 'combo', 'getUCAList', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'startUCA' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPM'))),
('Params', 'params', 'json', 'getUCAInputs', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'startUCA' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPM'))),
('Toolkit Name', 'toolkitName', 'text', '', '', '', '', 'true', (SELECT ID FROM command WHERE NAME = 'startUCA' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPM'))),
('Exception', 'exception', 'checkbox', '', 'true', 'false', '', '', (SELECT ID FROM command WHERE NAME = 'startServiceFlow' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPM'))),
('User', 'user', 'combo', 'getUserNameList', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'startServiceFlow' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPM'))),
('Service', 'service', 'combo', 'getServiceFlowList', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'startServiceFlow' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPM'))),
('Params', 'params', 'json', 'getServiceInputs', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'startServiceFlow' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPM'))),
('Expected Output', 'expectedOutput', 'json', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'startServiceFlow' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPM'))),
('Toolkit Name', 'toolkitName', 'text', '', '', '', '', 'true', (SELECT ID FROM command WHERE NAME = 'startServiceFlow' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPM'))),
('Json Path', 'jsonPath', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'startServiceFlow' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPM'))),
('Variable Name', 'variableName', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'startServiceFlow' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPM'))),
('User', 'user', 'combo', 'getUserNameList', '', '', '', 'BPMoC', (SELECT ID FROM command WHERE NAME = 'startAdHoc' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPM'))),
('Ad Hoc Name', 'adHocName', 'combo', 'getAdHocList', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'startAdHoc' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPM'))),
('User', 'user', 'combo', 'getUserNameList', '', '', '', 'BPMoC', (SELECT ID FROM command WHERE NAME = 'runAdHocActivity' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPM'))),
('Ad Hoc Activity Name', 'adHocActivityName', 'combo', 'getAdhocActivityList', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'runAdHocActivity' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPM'))),
('User', 'user', 'combo', 'getUserNameList', '', '', '', 'BPMoC', (SELECT ID FROM command WHERE NAME = 'runTaskByDisplayName' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPM'))),
('Task Name', 'taskName', 'combo', 'getAvailableTaskListByDisplayName', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'runTaskByDisplayName' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPM'))),
('User', 'user', 'combo', 'getUserNameList', '', '', '', 'BPMoC', (SELECT ID FROM command WHERE NAME = 'runTaskByActivityName' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPM'))),
('Task Name', 'taskName', 'combo', 'getAvailableTaskListByActivityName', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'runTaskByActivityName' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPM'))),
('User', 'user', 'combo', 'getUserNameList', '', '', '', 'BPMoC', (SELECT ID FROM command WHERE NAME = 'assignTask' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPM'))),
('Task Name', 'taskName', 'combo', 'getAvailableTaskListByActivityName', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'assignTask' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPM'))),
('To User', 'toUser', 'combo', 'getUserNameList', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'assignTask' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPM'))),
('User', 'user', 'combo', 'getUserNameList', '', '', '', 'BPMoC', (SELECT ID FROM command WHERE NAME = 'claimTask' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPM'))),
('Task Name', 'taskName', 'combo', 'getAvailableTaskListByActivityName', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'claimTask' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPM'))),
('User', 'user', 'combo', 'getUserNameList', '', '', '', 'BPMoC', (SELECT ID FROM command WHERE NAME = 'finishTask' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPM'))),
('Task Name', 'taskName', 'combo', 'getAvailableTaskListByActivityName', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'finishTask' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPM'))),
('Output', 'output', 'json', 'getTaskOutputs', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'finishTask' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPM'))),
('Instance ID', 'instanceId', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'addInstanceId' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPM'))),
('Task Name', 'taskName', 'combo', 'getAvailableTaskListByActivityName', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'getTaskIdByName' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPM'))),
('Process Name', 'processName', 'combo', 'getProcessList', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'getLatestInstanceIdByProcess' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPM'))),
('Process Name', 'processName', 'combo', 'getProcessList', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'getInstanceIdByInstanceName' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPM'))),
('Instance Name', 'instanceName', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'getInstanceIdByInstanceName' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPM'))),
('Process Name', 'processName', 'combo', 'getProcessList', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'getInstanceIdByTaskName' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPM'))),
('Task Name', 'taskName', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'getInstanceIdByTaskName' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPM'))),
('Process Name', 'processName', 'combo', 'getProcessList', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'getInstanceIdByBusinessData' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPM'))),
('Business Data Alias', 'businessDataAlias', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'getInstanceIdByBusinessData' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPM'))),
('Business Data Value', 'businessDataValue', 'text', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'getInstanceIdByBusinessData' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPM'))),
('User', 'user', 'combo', 'getUserNameList', '', '', '', 'BPMoC', (SELECT ID FROM command WHERE NAME = 'fireTimer' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPM'))),
('Token', 'token', 'combo', 'getTokenList', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'fireTimer' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPM'))),
('User', 'user', 'combo', 'getUserNameList', '', '', '', 'BPMoC', (SELECT ID FROM command WHERE NAME = 'startRestApi' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPM'))),
('API Name', 'apiName', 'combo', 'getRestApiListByDisplayName', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'startRestApi' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPM'))),
('Params', 'params', 'json', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'startRestApi' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPM'))),
('Expected Value', 'expectedValue', 'json', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'startRestApi' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPM'))),
('Instance Status', 'instanceStatus', 'combo', 'getInstanceStatusList', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'assertProcessInstanceStatus' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPMAssertion'))),
('Expected Value', 'expectedValue', 'json', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'assertProcessInstanceData' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPMAssertion'))),
('User', 'user', 'combo', 'getUserNameList', '', '', '', 'BPMoC', (SELECT ID FROM command WHERE NAME = 'assertTaskAssignmentByUser' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPMAssertion'))),
('Task Name', 'taskName', 'combo', 'getTaskListByActivityName', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'assertTaskAssignmentByUser' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPMAssertion'))),
('Task Name', 'taskName', 'combo', 'getTaskListByDisplayName', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'assertTaskStatus' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPMAssertion'))),
('Task Status', 'taskStatus', 'combo', 'getTaskStatus', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'assertTaskStatus' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPMAssertion'))),
('Task Name', 'taskName', 'combo', 'getTaskListByDisplayName', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'assertNextTaskName' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPMAssertion'))),
('Task Name', 'taskName', 'combo', 'getTaskListByDisplayName', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'assertTaskNotGenerated' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPMAssertion'))),
('User', 'user', 'combo', 'getUserNameList', '', '', '', 'BPMoC', (SELECT ID FROM command WHERE NAME = 'assertTaskData' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPMAssertion'))),
('Task Name', 'taskName', 'combo', 'getTaskListByDisplayName', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'assertTaskData' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPMAssertion'))),
('Expected Value', 'expectedValue', 'json', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'assertTaskData' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPMAssertion'))),
('Expected Value', 'expectedValue', 'json', '', '', '', '', '', (SELECT ID FROM command WHERE NAME = 'assertServiceData' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME = 'BPMAssertion')));

UPDATE command_parameter SET title='the default dataSourceName is jdbc/TeamWorksDB' WHERE parameter_name='dataSourceName';
UPDATE command_parameter SET title='Use json path to extract the output value or sub json' WHERE parameter_name='jsonPath';
UPDATE command_parameter SET title='Save Output into memory' WHERE parameter_name='variableName';
UPDATE command_parameter SET title='Run & Fill in Expected Output' WHERE parameter_name='expectedOutput' ;
UPDATE command_parameter SET title='Save the property of coach control binding value' WHERE parameter_name='property' AND COMMAND_ID = (SELECT ID FROM command WHERE NAME ='saveCoachControl' AND CATEGORY_ID = (SELECT ID FROM category WHERE NAME='UI'));
